import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import { Button, useColorMode } from "@chakra-ui/react";
const Chart = dynamic(() => import("../src/components/chart"), {
  ssr: false,
});

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <div>
      <Button onClick={toggleColorMode}>
        Toggle {colorMode === "light" ? "Dark" : "Light"}
      </Button>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Chart />
    </div>
  );
};

export default Home;
